from erpnext.accounts.doctype.payment_reconciliation.payment_reconciliation import PaymentReconciliation
from cust_payment_reconcilliation.overrides.custom_payment_reconcilliation import reconcile_allocations
PaymentReconciliation.reconcile_allocations = reconcile_allocations